# Generated by Django 3.2.9 on 2021-11-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_book',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AlterField(
            model_name='api_author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
