# Generated by Django 3.2.9 on 2021-11-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookstore', '0003_alter_api_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
            ],
        ),
    ]
