# Generated by Django 3.2.9 on 2021-11-16 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookstore', '0005_rename_added_by_id_api_author_added_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
