# Generated by Django 3.2.9 on 2022-01-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookstore', '0007_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
